/*
 * This file is generated by jOOQ.
*/
package org.tic.vertx.examples.web.ueditor.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.tic.vertx.examples.web.ueditor.jooq.tables.TUeditor;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUeditorRecord extends UpdatableRecordImpl<TUeditorRecord> implements Record4<Long, String, Long, Long> {

    private static final long serialVersionUID = -1341730297;

    /**
     * Setter for <code>test2.t_ueditor.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test2.t_ueditor.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test2.t_ueditor.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test2.t_ueditor.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test2.t_ueditor.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>test2.t_ueditor.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>test2.t_ueditor.updated_at</code>.
     */
    public void setUpdatedAt(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>test2.t_ueditor.updated_at</code>.
     */
    public Long getUpdatedAt() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TUeditor.T_UEDITOR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TUeditor.T_UEDITOR.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return TUeditor.T_UEDITOR.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return TUeditor.T_UEDITOR.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUeditorRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUeditorRecord value2(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUeditorRecord value3(Long value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUeditorRecord value4(Long value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUeditorRecord values(Long value1, String value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUeditorRecord
     */
    public TUeditorRecord() {
        super(TUeditor.T_UEDITOR);
    }

    /**
     * Create a detached, initialised TUeditorRecord
     */
    public TUeditorRecord(Long id, String content, Long createdAt, Long updatedAt) {
        super(TUeditor.T_UEDITOR);

        set(0, id);
        set(1, content);
        set(2, createdAt);
        set(3, updatedAt);
    }
}
