/*
 * This file is generated by jOOQ.
*/
package org.tic.vertx.examples.web.ueditor.jooq;


import javax.annotation.Generated;

import org.tic.vertx.examples.web.ueditor.jooq.tables.TUeditor;


/**
 * Convenience access to all tables in test2
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test2.t_ueditor</code>.
     */
    public static final TUeditor T_UEDITOR = org.tic.vertx.examples.web.ueditor.jooq.tables.TUeditor.T_UEDITOR;
}
