/*
 * This file is generated by jOOQ.
*/
package org.tic.vertx.examples.web.ueditor.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.tic.vertx.examples.web.ueditor.jooq.tables.TUeditor;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test2 extends SchemaImpl {

    private static final long serialVersionUID = 985394579;

    /**
     * The reference instance of <code>test2</code>
     */
    public static final Test2 TEST2 = new Test2();

    /**
     * The table <code>test2.t_ueditor</code>.
     */
    public final TUeditor T_UEDITOR = org.tic.vertx.examples.web.ueditor.jooq.tables.TUeditor.T_UEDITOR;

    /**
     * No further instances allowed
     */
    private Test2() {
        super("test2", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TUeditor.T_UEDITOR);
    }
}
